Coordinator:
  ros__parameters:
    main_tree_path: "/home/docker/ros2_ws/src/aip_coordinator/behaviors/examples/AIPDemoPose.xml"
    groot_palette_path: "/home/docker/ros2_ws/src/aip_coordinator/behaviors/GrootPalette.xml"
